title: Bryce Caine
theme: minima
baseurl: "" 
url: "https://brycecaine.github.io"
markdown: kramdown
header_pages:
  - index.md
  - blog.md
minima:
  social_links:
    - platform: github
      user_url: https://github.com/brycecaine
    - platform: twitter
      user_url: https://twitter.com/brycecaine
    - platform: linkedin
      user_url: https://linkedin.com/in/brycecaine

plugins:
  - jekyll-feed

prose:
  rooturl: "_posts"
  siteurl: "https://brycecaine.github.io"
  media: "assets"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Post Title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
